/* Auth Actions Types*/
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOG_OUT = "LOGOUT";

export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";

/* Profile Actions Types*/
export const CREATE_PROFILE_REQUEST = "CREATE_PROFILE_REQUEST";
export const CREATE_PROFILE_SUCCESS = "CREATE_PROFILE_SUCCESS";
export const CREATE_PROFILE_FAIL = "CREATE_PROFILE_FAIL";

export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";

export const DELETE_PROFILE_REQUEST = "DELETE_PROFILE_REQUEST";
export const DELETE_PROFILE_SUCCESS = "DELETE_PROFILE_SUCCESS";
export const DELETE_PROFILE_FAIL = "DELETE_PROFILE_FAIL";

/* Hotel Actions Types*/
export const CREATE_HOTEL_REQUEST = "CREATE_HOTEL_REQUEST";
export const CREATE_HOTEL_SUCCESS = "CREATE_HOTEL_SUCCESS";
export const CREATE_HOTEL_FAIL = "CREATE_HOTEL_FAIL";

export const UPDATE_HOTEL_REQUEST = "UPDATE_HOTEL_REQUEST";
export const UPDATE_HOTEL_SUCCESS = "UPDATE_HOTEL_SUCCESS";
export const UPDATE_HOTEL_FAIL = "UPDATE_HOTEL_FAIL";

export const GET_HOTEL_BY_ID_REQUEST = "GET_HOTEL_BY_ID_REQUEST";
export const GET_HOTEL_BY_ID_SUCCESS = "GET_HOTEL_BY_ID_SUCCESS";
export const GET_HOTEL_BY_ID_FAIL = "GET_HOTEL_BY_ID_FAIL";

export const DELETE_HOTEL_REQUEST = "DELETE_HOTEL_REQUEST";
export const DELETE_HOTEL_SUCCESS = "DELETE_HOTEL_SUCCESS";
export const DELETE_HOTEL_FAIL = "DELETE_HOTEL_FAIL";

/* Transport Actions Types*/
export const CREATE_TRANSPORT_REQUEST = "CREATE_TRANSPORT_REQUEST";
export const CREATE_TRANSPORT_SUCCESS = "CREATE_TRANSPORT_SUCCESS";
export const CREATE_TRANSPORT_FAIL = "CREATE_TRANSPORT_FAIL";
export const GET_ALL_TRANSPORT_REQUEST = "GET_ALL_TRANSPORT_REQUEST"
export const GET_ALL_TRANSPORT_SUCCESS = "GET_ALL_TRANSPORT_SUCCESS"
export const GET_ALL_TRANSPORT_FAIL = "GET_ALL_TRANSPORT_FAIL"

/* Plane Actions Types*/
export const CREATE_PLAN_REQUEST = "CREATE_PLAN_REQUEST";
export const CREATE_PLAN_SUCCESS = "CREATE_PLAN_SUCCESS";
export const CREATE_PLAN_FAIL = "CREATE_PLAN_FAIL";

export const GET_ALL_PLANS_REQUEST = "GET_ALL_PLANS_REQUEST";
export const GET_ALL_PLANS_SUCCESS = "GET_ALL_PLANS_SUCCESS";
export const GET_ALL_PLANS_FAIL = "GET_ALL_PLANS_FAIL";

export const GET_PLAN_BY_ID = "GET_PLAN_BY_ID";
export const GET_PLAN_BY_ID_SUCCESS = "GET_PLAN_BY_ID_SUCCESS";
export const GET_PLAN_BY_ID_FAIL = "GGET_PLAN_BY_ID_FAIL";

export const GET_PLAN_BY_NAME = "GET_PLAN_BY_NAME";
export const GET_PLAN_BY_NAME_SUCCESS = "GET_PLAN_BY_NAME_SUCCESS";
export const GET_PLAN_BY_NAME_FAIL = "GET_PLAN_BY_NAME_FAIL";

export const UPDATE_PLAN_SUCCESS = "UPDATE_PLAN_SUCCESS";
export const UPDATE_PLAN_FAIL = "UPDATE_PLAN_FAIL";

/* Tour Actions Types*/
export const CREATE_TOUR_REQUEST = "CREATE_TOUR_REQUEST";
export const CREATE_TOUR_SUCCESS = "CREATE_TOUR_SUCCESS";
export const CREATE_TOUR_FAIL = "CREATE_TOUR_FAIL";

/* Restaurant Actions Types*/
export const CREATE_RESTAURANT_REQUEST = "CREATE_RESTAURANT_REQUEST";
export const CREATE_RESTAURANT_SUCCESS = "CREATE_RESTAURANT_SUCCESS";
export const CREATE_RESTAURANT_FAIL = "CREATE_RESTAURANT_FAIL";






