export const CONSTANTS = {
  userNotFound: 'User not found',
  verifyEmailFirst: 'Verify email first',
  invalidCode: 'Invalid Code',
  alreadyVerified: 'Already Verified',
  passwordHashingRound: 8,
  incorrectEmailOrPassword: 'Incorrect email or password',
  somethingWentWrong: 'Something went wrong',
  defaultXlmAssetReqToActivateAccount: 5,
  assetNotExist: 'Asset not exists',
  notFound: 'Not found',
  invalidAccount: 'Invalid account',
  marketPairNotExist: 'Market pair not exist',
  tradeOfferNotExist: 'Trade offer not exist',
  distributorDontHaveEnoughBalance: `Distributor don't have enough balance`,
  accountAlreadyActivated: 'Account already activated',
  distributorDoesNotExist: 'Distributor account does not exist',
  emailAlreadyExist: 'Email already exist',
  coinNotFound: 'Coin not found',
  orderAlreadyAssigned: 'Order already assigned',
  notAuthorized: 'Not Authorized',
  etherGas: 21000,
  ERC20Gas: 80000,
  noSuchPackageFound: 'No such package found',
  noSuchSubscribedPackageFound: 'No such subscribed package found',
  noSuchSubscriptionPeriodFound: 'No such subscription period found',
  investmentOfThisTypeAlreadyExists: 'Investment of this type already exists',
  packageOfThisTypeAlreadyExists: 'Package of this type already exists',
  thisRaiseIsAlreadyAssignedToPackageOfThisCoin: 'This raise is already assigned to a package of this coin',
  baseAmountMaxAmountOrRaiseAlreadyExists: 'Duplicate Entry! Base amount or max amount or raise already exist',
  profitNotFound: 'Profit not found',
  sorryProfitIsInDistributionMode: 'Sorry! profit is in distribution mode',
  profitOfThisMonthAgainstThisCoinIsAlreadyAdded: 'Profit of this month against this coin is already added',
  packageHasAlreadyBeenUnsubscribed: 'Package has already been unsubscribed',
  insufficientAmount: 'Insufficient amount',
  cannotAddProfitOfUpcomingMonthsOrYears: 'Cannot add profit of upcoming months/years',
  referredUserNotExist: 'Referred user not exist',
};
